---
before:
  - 'ruby bin/build_keys'
after:
  - 'ruby bin/build_keys'
build_dependencies:
  - ImageMagick-devel
  - libxml2-devel
  - libxslt-devel
  - gcc
  - make
  - automake
dependencies:
  - mongodb-org-server
  - ImageMagick
  - libxml2
  - ImageMagick-c++
  - libxslt
targets:
  centos-7:
