--- 
build_dependencies: 
  - ImageMagick-devel
  - libxml2-devel
  - libxslt-devel
  - gcc
  - make
  - automake
dependencies: 
  - mongodb-org-server
  - ImageMagick
  - libxml2
  - ImageMagick-c++
  - libxslt
targets:
  centos-7:
  
