version: '3'

services:
  db:
    build: "./dockerfiles/database"
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
      - "28017:28017"
  web:
    build:
      context: ./
      dockerfile: ./dockerfiles/heimdall/Dockerfile
    ports:
      - "4567:4567"
    depends_on:
      - "db"
